### ISSUE TITLE
Does this set of parameters crash the MARKII test for you?

### ISSUE THREAD

**Issue by bamos** [WalnutiQ/callWalnutiQ#7]
```
> java -cp WalnutIQLib/CallMARKIISingle.jar:WalnutIQLib/WalnutIQ.jar:WalnutIQLib/mnist-tools.jar RunMARKIISingle  1.000000000000000000000000000000E+00  7.897848242173036048541234777076E+00  5.385647704178850858625082764775E+01  3.201692771346944255128619261086E+01  5.573149187962278119812253862619E+03
Exception in thread "main" java.lang.NullPointerException
	at model.MARK_II.TemporalPooler.adaptSegments(TemporalPooler.java:377)
	at model.MARK_II.TemporalPooler.phaseThree(TemporalPooler.java:354)
	at model.MARK_II.TemporalPooler.performTemporalPoolingOnRegion(TemporalPooler.java:61)
	at model.MARK_II.parameters.FindOptimalParametersForSPandTP.printToFileSPandTPScoreFor1RetinaTo1RegionModelFor1Digit(FindOptimalParametersForSPandTP.java:49)
	at RunMARKIISingle.main(RunMARKIISingle.java:18)
```

**Comment by quinnliu** [comment]
Fixed a long time ago.
